# Pandas Parte 10
## Data Cleaning
En este notebook exploraremos técnicas adicionales de limpieza de datos. Aprenderemos a cambiar tipos de datos, interpolar y eliminar duplicados.

### Plan de aprendizaje:
- Casting: convertir tipos de datos (astype)
- Métodos de interpolación (ffill, bfill)
- Eliminar duplicados (drop_duplicates)
- Limpiar espacios en blanco en strings

In [2]:
import pandas as pd
import numpy as np

## Casting: Conversión de Tipos de Datos
Cambiar el tipo de dato de una columna usando astype().

In [3]:
# Crear un DataFrame de ejemplo
data = {'YearsCode': ['1', '2', '3', 'Less than 1 year', '5', 'More than 50 years', '10']}
df = pd.DataFrame(data)
df

            YearsCode
0                   1
1                   2
2                   3
3    Less than 1 year
4                   5
5  More than 50 years
6                  10

In [4]:
# Intentar convertir a float directamente (generará error)
# df['YearsCode'].astype(float)  # Esto causará error

# Primero, reemplazar valores textuales con numéricos
df['YearsCode'].replace({'Less than 1 year': 0, 'More than 50 years': 55}, inplace=True)
df

C:\Users\Vaquin\AppData\Local\Temp\ipykernel_2064\1320387190.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['YearsCode'].replace({'Less than 1 year': 0, 'More than 50 years': 55}, inplace=True)

  YearsCode
0         1
1         2
2         3
3         0
4         5
5        55
6        10

In [5]:
# Ahora convertir a float
df['YearsCode'] = df['YearsCode'].astype(float)
df['YearsCode'].mean()

np.float64(10.857142857142858)

## Métodos de Interpolación: ffill y bfill
ffill: forward fill (propagar valores hacia adelante)
bfill: backward fill (propagar valores hacia atrás)

In [6]:
# Crear un DataFrame con valores faltantes
data = pd.DataFrame(np.random.randn(7, 3))
data.iloc[:3, 1] = np.nan
data.iloc[:2, 2] = np.nan
data.iloc[4:6, 2] = np.nan
data

          0         1         2
0  0.426118       NaN       NaN
1 -1.200130       NaN       NaN
2 -0.196862       NaN -0.236632
3 -1.778418 -0.492904 -1.126015
4  1.747850 -0.569191       NaN
5 -0.230371  0.466085       NaN
6 -0.527410 -1.479539  0.128397

In [7]:
# Forward fill: propagar el último valor conocido hacia adelante
data.fillna(method='ffill')

C:\Users\Vaquin\AppData\Local\Temp\ipykernel_2064\1172370733.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')

          0         1         2
0  0.426118       NaN       NaN
1 -1.200130       NaN       NaN
2 -0.196862       NaN -0.236632
3 -1.778418 -0.492904 -1.126015
4  1.747850 -0.569191 -1.126015
5 -0.230371  0.466085 -1.126015
6 -0.527410 -1.479539  0.128397

In [8]:
# Backward fill: propagar el siguiente valor conocido hacia atrás
data.fillna(method='bfill')

C:\Users\Vaquin\AppData\Local\Temp\ipykernel_2064\1440667032.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')

          0         1         2
0  0.426118 -0.492904 -0.236632
1 -1.200130 -0.492904 -0.236632
2 -0.196862 -0.492904 -0.236632
3 -1.778418 -0.492904 -1.126015
4  1.747850 -0.569191  0.128397
5 -0.230371  0.466085  0.128397
6 -0.527410 -1.479539  0.128397

In [9]:
# ffill con límite: solo llenar hasta N valores
data.fillna(method='ffill', limit=1)

C:\Users\Vaquin\AppData\Local\Temp\ipykernel_2064\3764988500.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', limit=1)

          0         1         2
0  0.426118       NaN       NaN
1 -1.200130       NaN       NaN
2 -0.196862       NaN -0.236632
3 -1.778418 -0.492904 -1.126015
4  1.747850 -0.569191 -1.126015
5 -0.230371  0.466085       NaN
6 -0.527410 -1.479539  0.128397

## Eliminando Duplicados
Usar duplicated() para detectar y drop_duplicates() para eliminar.

In [10]:
# Crear un DataFrame con duplicados
data1 = pd.DataFrame({'col1': ['one', 'two'] * 4 + ['two'], 
                      'col2': [1, 1, 2, 3, 3, 4, 4, 5, 5]})
data1

  col1  col2
0  one     1
1  two     1
2  one     2
3  two     3
4  one     3
5  two     4
6  one     4
7  two     5
8  two     5

In [11]:
# Detectar duplicados (retorna valores booleanos)
data1.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
dtype: bool

In [12]:
# Contar el número de duplicados
data1.duplicated().sum()

np.int64(1)

In [13]:
# Eliminar duplicados
data1_clean = data1.drop_duplicates()
data1_clean

  col1  col2
0  one     1
1  two     1
2  one     2
3  two     3
4  one     3
5  two     4
6  one     4
7  two     5

## Conclusión
La limpieza de datos es un proceso continuo y esencial. Un dataset bien limpio es fundamental para análisis precisos y modelos de ML de alta calidad.