# Pandas Parte 7
## Sorting Data
En este notebook exploraremos cómo ordenar datos en Pandas. El ordenamiento es esencial para comprensión, análisis y visualización de datos.

### Plan de aprendizaje:
- Ordenar basándose en una columna
- Ordenar basándose en múltiples columnas
- Ordenar basándose en índices
- Métodos adicionales: nlargest() y nsmallest()

In [2]:
import pandas as pd
import numpy as np

## Ordenando por una Columna
Usar sort_values() para ordenar datos en orden ascendente o descendente.

In [3]:
# Crear un DataFrame de ejemplo
df = pd.DataFrame({
    'Name': ['John', 'Jane', 'Bob', 'Alice'],
    'Age': [25, 30, 22, 28],
    'Salary': [50000, 60000, 45000, 55000]
})
df

    Name  Age  Salary
0   John   25   50000
1   Jane   30   60000
2    Bob   22   45000
3  Alice   28   55000

In [4]:
# Ordenar por columna Country en orden ascendente
df.sort_values(by='Age')

    Name  Age  Salary
2    Bob   22   45000
0   John   25   50000
3  Alice   28   55000
1   Jane   30   60000

In [5]:
# Ordenar por columna Country en orden descendente
df.sort_values(by='Age', ascending=False)

    Name  Age  Salary
1   Jane   30   60000
3  Alice   28   55000
0   John   25   50000
2    Bob   22   45000

## Ordenando por Múltiples Columnas
Pasar una lista de columnas a sort_values() para ordenar por varias columnas.

In [6]:
# Ordenar por múltiples columnas (Age ascendente, Salary descendente)
df.sort_values(by=['Age', 'Salary'], ascending=[True, False])

    Name  Age  Salary
2    Bob   22   45000
0   John   25   50000
3  Alice   28   55000
1   Jane   30   60000

## Ordenando por Índice
Usar sort_index() para ordenar los índices (filas o columnas).

In [7]:
# Ordenar por índice en orden ascendente
df.sort_index()

    Name  Age  Salary
0   John   25   50000
1   Jane   30   60000
2    Bob   22   45000
3  Alice   28   55000

In [8]:
# Ordenar por índice en orden descendente
df.sort_index(ascending=False)

    Name  Age  Salary
3  Alice   28   55000
2    Bob   22   45000
1   Jane   30   60000
0   John   25   50000

In [9]:
# Ordenar nombres de columnas en orden alfabético
df.sort_index(axis='columns')

   Age   Name  Salary
0   25   John   50000
1   30   Jane   60000
2   22    Bob   45000
3   28  Alice   55000

## Métodos Adicionales: nlargest() y nsmallest()
Obtener los n valores más grandes o más pequeños de una columna.

In [10]:
# Obtener las 2 filas con los salarios más altos
df.nlargest(2, 'Salary')

    Name  Age  Salary
1   Jane   30   60000
3  Alice   28   55000

In [11]:
# Obtener los 2 valores más grandes de la columna Salary
df['Salary'].nlargest(2)

1    60000
3    55000
Name: Salary, dtype: int64

In [12]:
# Obtener las 2 filas con las edades más bajas
df.nsmallest(2, 'Age')

   Name  Age  Salary
2   Bob   22   45000
0  John   25   50000

In [13]:
# Obtener los 2 valores más pequeños de la columna Age
df['Age'].nsmallest(2)

2    22
0    25
Name: Age, dtype: int64

## Conclusión
El ordenamiento es fundamental en análisis de datos. Permite identificar patrones, encontrar extremos y preparar datos para visualización e insights significativos.