# Pandas Parte 8
## Updating Rows and Columns
En este notebook exploraremos cómo actualizar filas y columnas en DataFrames. Aprender a modificar datos es esencial para la limpieza de datos.

### Plan de aprendizaje:
- Actualizar nombres de columnas
- Actualizar filas completas
- Actualizar filas específicas basándose en condiciones
- Usar apply, map y replace para transformaciones

In [2]:
import pandas as pd
import numpy as np

## Actualizando Nombres de Columnas
Usar rename() para cambiar nombres de columnas de forma permanente.

In [3]:
# Crear un DataFrame de ejemplo
Student = {
    "Id": ['cs-01', 'mth-02', 'eng-03', 'phy-04', 'mth-05', 'cs-06'],
    "Name": ["Fatima Khan", 'Noureen Ali', 'Salman Aslam', 'Sana Khan', 'Adam Jack', 'Ali Khan'],
    "subject": ['computer science', 'math', 'english', 'physics', 'statistics', 'programming'],
    "marks": [45, 90, 60, 37, 49, 50]
}
data = pd.DataFrame(Student)
data

       Id          Name           subject  marks
0   cs-01   Fatima Khan  computer science     45
1  mth-02   Noureen Ali              math     90
2  eng-03  Salman Aslam           english     60
3  phy-04     Sana Khan           physics     37
4  mth-05     Adam Jack        statistics     49
5   cs-06      Ali Khan       programming     50

In [4]:
# Renombrar una columna específica
data.rename(columns={'Name': 'Full Name'}, inplace=True)
data

       Id     Full Name           subject  marks
0   cs-01   Fatima Khan  computer science     45
1  mth-02   Noureen Ali              math     90
2  eng-03  Salman Aslam           english     60
3  phy-04     Sana Khan           physics     37
4  mth-05     Adam Jack        statistics     49
5   cs-06      Ali Khan       programming     50

In [5]:
# Convertir todos los nombres de columnas a minúsculas
data.columns = data.columns.str.lower()
data

       id     full name           subject  marks
0   cs-01   Fatima Khan  computer science     45
1  mth-02   Noureen Ali              math     90
2  eng-03  Salman Aslam           english     60
3  phy-04     Sana Khan           physics     37
4  mth-05     Adam Jack        statistics     49
5   cs-06      Ali Khan       programming     50

## Actualizando Filas
Usar loc[] para actualizar filas completas o valores específicos.

In [6]:
# Seleccionar una fila completa
data.loc[4]

id               mth-05
full name     Adam Jack
subject      statistics
marks                49
Name: 4, dtype: object

In [7]:
# Actualizar una fila completa
data.loc[4] = ['cs-05', 'Ali', 'Database', 47]
data.loc[4]

id              cs-05
full name         Ali
subject      Database
marks              47
Name: 4, dtype: object

In [8]:
# Seleccionar columnas específicas de una fila
data.loc[0, ['name', 'subject']]

KeyError: "['name'] not in index"

In [ ]:
# Actualizar solo columnas específicas
data.loc[0, ['name', 'subject']] = ['Farhan', 'Python']
data.loc[0, ['name', 'subject']]

## Actualizando Filas Basándose en Condiciones
Usar condiciones booleanas con loc[] para actualizar múltiples filas.

In [ ]:
# Crear una condición: notas menores a 50
filt = data['marks'] < 50
filt

In [ ]:
# Actualizar filas que cumplen la condición
data.loc[filt, 'marks'] = 'Fail'
data

## Conclusión
Actualizar filas y columnas es esencial para la limpieza y preparación de datos. Esto permite transformar datos crudos en información analizable.