# Advanced Indexing in Pandas

Learn to work with hierarchical multi-level indexes in Pandas for complex data structures.

In [31]:
import pandas as pd
import numpy as np

## Series with MultiIndex

Create a Series with hierarchical two-level indexes.

In [32]:
# Create a Series with MultiIndex
arrays = [['Team1', 'Team1', 'Team1', 'Team2', 'Team2', 'Team2', 'Team3', 'Team3', 'Team3'],
          ['player_1', 'player_2', 'player_3', 'player_1', 'player_2', 'player_3', 'player_1', 'player_2', 'player_3']]
index = pd.MultiIndex.from_arrays(arrays)
data = pd.Series([56, 78, 99, 56, 88, 59, 100, 57, 91], index=index, name="Player's Score")
data

Team1  player_1     56
       player_2     78
       player_3     99
Team2  player_1     56
       player_2     88
       player_3     59
Team3  player_1    100
       player_2     57
       player_3     91
Name: Player's Score, dtype: int64

In [33]:
# View the MultiIndex of the Series
data.index

MultiIndex([('Team1', 'player_1'),
            ('Team1', 'player_2'),
            ('Team1', 'player_3'),
            ('Team2', 'player_1'),
            ('Team2', 'player_2'),
            ('Team2', 'player_3'),
            ('Team3', 'player_1'),
            ('Team3', 'player_2'),
            ('Team3', 'player_3')],
           )

In [34]:
# Select a range from level 0
data['Team1':'Team2']

Team1  player_1    56
       player_2    78
       player_3    99
Team2  player_1    56
       player_2    88
       player_3    59
Name: Player's Score, dtype: int64

## DataFrame with MultiIndex

Use set_index() to convert columns into MultiIndex.

In [35]:
# Create a sample DataFrame
df = pd.DataFrame({
    'city': ['New York', 'New York', 'Los Angeles', 'Los Angeles', 'Chicago', 'Chicago'],
    'rank': [1, 2, 1, 2, 1, 2],
    'population': [8000000, 7000000, 4000000, 3500000, 2700000, 2300000],
    'area': [302, 302, 469, 469, 227, 227]
})
df

          city  rank  population  area
0     New York     1     8000000   302
1     New York     2     7000000   302
2  Los Angeles     1     4000000   469
3  Los Angeles     2     3500000   469
4      Chicago     1     2700000   227
5      Chicago     2     2300000   227

In [36]:
# Set city and rank as MultiIndex
df.set_index(['city', 'rank'], inplace=True)
df

                  population  area
city        rank
New York    1        8000000   302
            2        7000000   302
Los Angeles 1        4000000   469
            2        3500000   469
Chicago     1        2700000   227
            2        2300000   227

## Accessing MultiIndex Data

Access data using hierarchical index levels.

In [37]:
# View the MultiIndex
df.index

MultiIndex([(   'New York', 1),
            (   'New York', 2),
            ('Los Angeles', 1),
            ('Los Angeles', 2),
            (    'Chicago', 1),
            (    'Chicago', 2)],
           names=['city', 'rank'])

In [38]:
# Select a specific record using MultiIndex
df.loc['New York', 1]

population    8000000
area              302
Name: (New York, 1), dtype: int64

## Reshaping: Stack and Unstack

Transform hierarchical index levels and columns.

In [39]:
# Unstack: pivot innermost index level to columns
df.unstack()

            population          area
rank                 1        2    1    2
city
Chicago        2700000  2300000  227  227
Los Angeles    4000000  3500000  469  469
New York       8000000  7000000  302  302

In [40]:
# Stack: pivot columns to index
df.stack()

city         rank
New York     1     population    8000000
                   area              302
             2     population    7000000
                   area              302
Los Angeles  1     population    4000000
                   area              469
             2     population    3500000
                   area              469
Chicago      1     population    2700000
                   area              227
             2     population    2300000
                   area              227
dtype: int64

## Sorting by Index Level

Sort data using the level parameter to specify which index level to sort by.

In [41]:
# Sort by level 0 (city)
df.sort_index(level=0)

                  population  area
city        rank
Chicago     1        2700000   227
            2        2300000   227
Los Angeles 1        4000000   469
            2        3500000   469
New York    1        8000000   302
            2        7000000   302

In [42]:
# Sort by level 1 (rank)
df.sort_index(level=1)

                  population  area
city        rank
Chicago     1        2700000   227
Los Angeles 1        4000000   469
New York    1        8000000   302
Chicago     2        2300000   227
Los Angeles 2        3500000   469
New York    2        7000000   302

## Conclusion

Advanced indexing with MultiIndex allows efficient work with hierarchical data structures. It's powerful for multidimensional analysis.