# Pandas Parte 9
## Handling Missing Values
En este notebook exploraremos cómo detectar, eliminar y rellenar valores faltantes. Los valores NaN son comunes en datos reales y deben manejarse correctamente.

### Plan de aprendizaje:
- Detectar valores nulos (isnull, notnull)
- Eliminar valores nulos (dropna)
- Lidiar con valores faltantes personalizados
- Rellenar datos faltantes (fillna)

In [14]:
import pandas as pd
import numpy as np

## Detectando Valores Nulos
Usar isnull() para identificar valores faltantes (NaN, None).

In [15]:
# Crear un DataFrame con valores faltantes y valores textuales que parecen nulos
student = {
    'first': ['Fatima', 'Carine', 'Alla', 'Salman', np.nan, None, 'NA'],
    'last': ['Khan', 'Aries', 'Ben', 'Malik', np.nan, np.nan, 'NaN'],
    'email': ['fatimakhan@gmail.com', 'caries@email.com', 'allaben@gmail.com', None, np.nan, 'saqib@gmail.com', 'NA'],
    'age': [33, 55, 63, 36, np.nan, None, '?']
}
data = pd.DataFrame(student)
data

    first   last                 email   age
0  Fatima   Khan  fatimakhan@gmail.com    33
1  Carine  Aries      caries@email.com    55
2    Alla    Ben     allaben@gmail.com    63
3  Salman  Malik                  None    36
4     NaN    NaN                   NaN   NaN
5    None    NaN       saqib@gmail.com  None
6      NA    NaN                    NA     ?

In [16]:
# Detectar valores nulos con isnull()
data.isnull()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6  False  False  False  False

In [17]:
# Contar valores nulos por columna
data.isnull().sum()

first    2
last     2
email    2
age      2
dtype: int64

## Eliminando Valores Nulos
Usar dropna() para eliminar filas o columnas con valores faltantes.

In [18]:
# Eliminar filas con AL MENOS un valor nulo (how='any')
data.dropna(how='any')

    first   last                 email age
0  Fatima   Khan  fatimakhan@gmail.com  33
1  Carine  Aries      caries@email.com  55
2    Alla    Ben     allaben@gmail.com  63
6      NA    NaN                    NA   ?

In [19]:
# Eliminar columnas con AL MENOS un valor nulo (axis=1)
data.dropna(how='any', axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [20]:
# Eliminar columnas solo si TODAS tienen valores nulos (how='all', axis=1)
data.dropna(how='all', axis=1)

    first   last                 email   age
0  Fatima   Khan  fatimakhan@gmail.com    33
1  Carine  Aries      caries@email.com    55
2    Alla    Ben     allaben@gmail.com    63
3  Salman  Malik                  None    36
4     NaN    NaN                   NaN   NaN
5    None    NaN       saqib@gmail.com  None
6      NA    NaN                    NA     ?

## Manejando Valores Faltantes Personalizados
Convertir valores textuales que parecen nulos (como 'NA', 'NaN', '?') en NaN verdaderos.

In [21]:
# Reemplazar valores textuales que parecen nulos con NaN verdaderos
data.replace({'NA': np.nan, 'NaN': np.nan, '?': np.nan}, inplace=True)
data

C:\Users\Vaquin\AppData\Local\Temp\ipykernel_17028\2054303296.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({'NA': np.nan, 'NaN': np.nan, '?': np.nan}, inplace=True)

    first   last                 email   age
0  Fatima   Khan  fatimakhan@gmail.com  33.0
1  Carine  Aries      caries@email.com  55.0
2    Alla    Ben     allaben@gmail.com  63.0
3  Salman  Malik                  None  36.0
4     NaN    NaN                   NaN   NaN
5    None    NaN       saqib@gmail.com   NaN
6     NaN    NaN                   NaN   NaN

In [22]:
# Ahora eliminar todas las filas con valores nulos (incluyendo los que acabamos de convertir)
data.dropna()

    first   last                 email   age
0  Fatima   Khan  fatimakhan@gmail.com  33.0
1  Carine  Aries      caries@email.com  55.0
2    Alla    Ben     allaben@gmail.com  63.0

## Rellenando Valores Faltantes
Usar fillna() para llenar valores nulos con un valor específico o estadístico.

In [23]:
# Recrear el DataFrame original para llenar en lugar de eliminar
student = {
    'first': ['Fatima', 'Carine', 'Alla', 'Salman', np.nan, None, 'NA'],
    'last': ['Khan', 'Aries', 'Ben', 'Malik', np.nan, np.nan, 'NaN'],
    'email': ['fatimakhan@gmail.com', 'caries@email.com', 'allaben@gmail.com', None, np.nan, 'saqib@gmail.com', 'NA'],
    'age': [33, 55, 63, 36, np.nan, None, '?']
}
data = pd.DataFrame(student)
data.replace({'NA': np.nan, 'NaN': np.nan, '?': np.nan}, inplace=True)
data

C:\Users\Vaquin\AppData\Local\Temp\ipykernel_17028\435145809.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({'NA': np.nan, 'NaN': np.nan, '?': np.nan}, inplace=True)

    first   last                 email   age
0  Fatima   Khan  fatimakhan@gmail.com  33.0
1  Carine  Aries      caries@email.com  55.0
2    Alla    Ben     allaben@gmail.com  63.0
3  Salman  Malik                  None  36.0
4     NaN    NaN                   NaN   NaN
5    None    NaN       saqib@gmail.com   NaN
6     NaN    NaN                   NaN   NaN

In [24]:
# Llenar todos los NaN con un valor específico
data.fillna('MISSING')

     first     last                 email      age
0   Fatima     Khan  fatimakhan@gmail.com     33.0
1   Carine    Aries      caries@email.com     55.0
2     Alla      Ben     allaben@gmail.com     63.0
3   Salman    Malik               MISSING     36.0
4  MISSING  MISSING               MISSING  MISSING
5  MISSING  MISSING       saqib@gmail.com  MISSING
6  MISSING  MISSING               MISSING  MISSING

In [25]:
# Llenar NaN en la columna 'age' con la media (solo para columnas numéricas)
# Primero convertir 'age' a numérico
data_numeric = data.copy()
data_numeric['age'] = pd.to_numeric(data_numeric['age'], errors='coerce')
data_numeric['age'].fillna(data_numeric['age'].mean(), inplace=True)
data_numeric

C:\Users\Vaquin\AppData\Local\Temp\ipykernel_17028\3809694168.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_numeric['age'].fillna(data_numeric['age'].mean(), inplace=True)

    first   last                 email    age
0  Fatima   Khan  fatimakhan@gmail.com  33.00
1  Carine  Aries      caries@email.com  55.00
2    Alla    Ben     allaben@gmail.com  63.00
3  Salman  Malik                  None  36.00
4     NaN    NaN                   NaN  46.75
5    None    NaN       saqib@gmail.com  46.75
6     NaN    NaN                   NaN  46.75

## Conclusión
El manejo de valores faltantes es crítico en ciencia de datos. Elegir entre eliminar o rellenar datos afecta directamente la calidad del análisis y el rendimiento de modelos de ML.