# Pandas Parte 6
## Adding and Dropping Rows and Columns
En este notebook exploraremos cómo agregar y eliminar filas y columnas, así como combinar datasets. Estos son conceptos clave para la preparación de datos.

### Plan de aprendizaje:
- Agregar columnas con operador de indexación
- Agregar columnas con método Insert
- Eliminar columnas
- Agregar filas con método Concat
- Eliminar filas

In [13]:
import pandas as pd

## Agregando Columnas con Operador de Indexación
Crear nuevas columnas asignando cálculos a un nombre de columna inexistente.

In [14]:
# Crear un DataFrame de ejemplo
df = pd.DataFrame({
    'Category': ['Breakfast', 'Breakfast', 'Lunch', 'Lunch', 'Dinner'],
    'Item': ['Eggs', 'Toast', 'Burger', 'Salad', 'Pasta'],
    'Calories': [155, 100, 354, 150, 220],
    'Carbohydrates': [1.1, 14, 36, 4, 43],
    'Protein': [13, 4, 12, 8, 9]
})
df

    Category    Item  Calories  Carbohydrates  Protein
0  Breakfast    Eggs       155            1.1       13
1  Breakfast   Toast       100           14.0        4
2      Lunch  Burger       354           36.0       12
3      Lunch   Salad       150            4.0        8
4     Dinner   Pasta       220           43.0        9

In [15]:
# Agregar una columna calculada: Carbohydrates Percentage
df['Carbohydrates Percentage'] = df['Carbohydrates'] / df['Calories'] * 100
df.loc[:, ['Category', 'Item', 'Calories', 'Carbohydrates', 'Carbohydrates Percentage']]

    Category    Item  Calories  Carbohydrates  Carbohydrates Percentage
0  Breakfast    Eggs       155            1.1                  0.709677
1  Breakfast   Toast       100           14.0                 14.000000
2      Lunch  Burger       354           36.0                 10.169492
3      Lunch   Salad       150            4.0                  2.666667
4     Dinner   Pasta       220           43.0                 19.545455

## Agregando Columnas con Insert Method
Insertar una columna en una posición específica.

In [16]:
# Insertar una columna en la posición 4
df.insert(4, 'Protein Percentage', df['Protein'] / df['Calories'] * 100, False)
df.head()

,Category,Item,Calories,Carbohydrates,Protein Percentage,Protein,Carbohydrates Percentage
0,Breakfast,Eggs,155,1.1,8.387097,13,0.709677
1,Breakfast,Toast,100,14.0,4.000000,4,14.000000
2,Lunch,Burger,354,36.0,3.389831,12,10.169492
3,Lunch,Salad,150,4.0,5.333333,8,2.666667
4,Dinner,Pasta,220,43.0,4.090909,9,19.545455

## Eliminando Columnas
Usar drop() para eliminar columnas.

In [17]:
# Eliminar una columna
df.drop(columns='Protein Percentage', inplace=True)
df.head()

,Category,Item,Calories,Carbohydrates,Protein,Carbohydrates Percentage
0,Breakfast,Eggs,155,1.1,13,0.709677
1,Breakfast,Toast,100,14.0,4,14.000000
2,Lunch,Burger,354,36.0,12,10.169492
3,Lunch,Salad,150,4.0,8,2.666667
4,Dinner,Pasta,220,43.0,9,19.545455

## Agregando Filas con Concat
Combinar dos DataFrames usando concat().

In [18]:
# Crear primer DataFrame
student1 = {
    'Id': ['cs-01', 'mth-02', 'eng-03', 'phy-04', 'mth-05', 'cs-06'],
    'Name': ['Fatima', 'Noureen', 'Salman', 'Sana', 'Jack', 'Ali'],
    'subject': ['computer science', 'math', 'english', 'physics', 'statistics', 'programming'],
    'marks': [45, 90, 60, 37, 49, 50]
}
data1 = pd.DataFrame(student1)
data1

       Id     Name           subject  marks
0   cs-01   Fatima  computer science     45
1  mth-02  Noureen              math     90
2  eng-03   Salman           english     60
3  phy-04     Sana           physics     37
4  mth-05     Jack        statistics     49
5   cs-06      Ali       programming     50

In [19]:
# Crear segundo DataFrame
student2 = {
    'Id': ['cs-08', 'mth-07'],
    'Name': ['Adam', 'Steve'],
    'subject': ['computer science', 'math'],
    'marks': [45, 90]
}
data2 = pd.DataFrame(student2)
data2

       Id   Name           subject  marks
0   cs-08   Adam  computer science     45
1  mth-07  Steve              math     90

In [20]:
# Concatenar por filas (axis=0) manteniendo índices originales
pd.concat([data1, data2], ignore_index=False)

       Id     Name           subject  marks
0   cs-01   Fatima  computer science     45
1  mth-02  Noureen              math     90
2  eng-03   Salman           english     60
3  phy-04     Sana           physics     37
4  mth-05     Jack        statistics     49
5   cs-06      Ali       programming     50
0   cs-08     Adam  computer science     45
1  mth-07    Steve              math     90

In [21]:
# Concatenar por filas (axis=0) reseteando índices
pd.concat([data1, data2], ignore_index=True)

       Id     Name           subject  marks
0   cs-01   Fatima  computer science     45
1  mth-02  Noureen              math     90
2  eng-03   Salman           english     60
3  phy-04     Sana           physics     37
4  mth-05     Jack        statistics     49
5   cs-06      Ali       programming     50
6   cs-08     Adam  computer science     45
7  mth-07    Steve              math     90

In [22]:
# Concatenar por columnas (axis=1)
pd.concat([data1, data2], axis=1)

,Id,Name,subject,marks,Id,Name,subject,marks
0,cs-01,Fatima,computer science,45,cs-08,Adam,computer science,45.0
1,mth-02,Noureen,math,90,mth-07,Steve,math,90.0
2,eng-03,Salman,english,60,NaN,NaN,NaN,NaN
3,phy-04,Sana,physics,37,NaN,NaN,NaN,NaN
4,mth-05,Jack,statistics,49,NaN,NaN,NaN,NaN
5,cs-06,Ali,programming,50,NaN,NaN,NaN,NaN

## Eliminando Filas
Usar drop() con el parámetro index para eliminar filas.

In [23]:
# Concatenar y resetear índice
data1_combined = pd.concat([data1, data2], axis=0, ignore_index=True)
data1_combined

       Id     Name           subject  marks
0   cs-01   Fatima  computer science     45
1  mth-02  Noureen              math     90
2  eng-03   Salman           english     60
3  phy-04     Sana           physics     37
4  mth-05     Jack        statistics     49
5   cs-06      Ali       programming     50
6   cs-08     Adam  computer science     45
7  mth-07    Steve              math     90

In [24]:
# Eliminar filas específicas
data1_combined.drop(index=[0, 7])

       Id     Name           subject  marks
1  mth-02  Noureen              math     90
2  eng-03   Salman           english     60
3  phy-04     Sana           physics     37
4  mth-05     Jack        statistics     49
5   cs-06      Ali       programming     50
6   cs-08     Adam  computer science     45

## Conclusión
Agregar y eliminar filas y columnas es fundamental para la preparación y limpieza de datos. Estas operaciones son esenciales para preparar datasets para análisis.